---
title: "Digital Tools for Reproducible Research"
---

Here you will find the materials associated with _Digital Tools for Reproducible Research: A reproducible project from start to finish_, in the 
[Department of Education, University of York](https://www.york.ac.uk/education/).


This series of 6 brownbags provides a practical introduction to digital tools needed to complete a reproducible research project. Each session will move through a successive stage of a project, with a focus on tangible outputs (e.g. OSF project page, preregistration, analysis script and power analysis, reproducible manuscript template). 

The brownbags are aimed at researchers (staff and PhD) who already have a reasonable grounding in data analysis and experimental/study design. Some sessions (e.g. data simulation) will be focused on quantitative analyses. Knowledge of the R statistical programming language is not assumed, and while scripts will be provided to get started in appropriate sessions, the sessions are not a complete introduction to R.

It is envisaged that participants may take the opportunity to work on a planned empirical study, and will finish the sessions with a completed preregistration which includes analysis scripts and power estimates, as well as the template for the manuscript. The sessions can be scaled by focusing on a replication of a published paper. 

Sessions:   
1. Week 5 Reproducible research  
2. Week 6 Preregistration  
3. Week 7 Open data   
4. Week 8 Reproducible analyses, power analysis and simulation  
5. Week 9 Writing a reproducible manuscript  
6. Week 10 Preprints and repositories  
